"""
summarize.py - Aggregate result JSONs into summary markdown and combined JSON.

The results directory contains multiple schemas (probe analysis, best-of-N,
prefix analysis, prefix filtering). This summarizer renders sections only for
schemas it recognizes and skips incompatible ones.
"""
import json
import math
import os
import argparse
from pathlib import Path


def load_results(results_dir: str) -> dict:
    """Load all result JSONs into a nested dict: {model: {dataset: data}}."""
    results = {}
    base = Path(results_dir)
    for model_dir in sorted(base.iterdir()):
        if not model_dir.is_dir():
            continue
        model = model_dir.name
        results[model] = {}
        for ds_dir in sorted(model_dir.iterdir()):
            if not ds_dir.is_dir():
                continue
            ds = ds_dir.name
            json_files = sorted([f for f in ds_dir.iterdir() if f.suffix == ".json"])
            if not json_files:
                continue
            # Prefer canonical stage outputs; fall back to first JSON if needed.
            chosen = None
            for f in json_files:
                if f.name.endswith("_results.json"):
                    chosen = f
                    break
            if chosen is None:
                chosen = json_files[0]
            with open(chosen) as fh:
                results[model][ds] = json.load(fh)
    return results


def is_probe_result(data: dict) -> bool:
    """Main analyze.py schema with layer AUCs and class counts."""
    return isinstance(data, dict) and all(
        key in data for key in ("n_correct", "n_incorrect", "entropy_baseline", "layers")
    )


def is_prefix_filter_result(data: dict) -> bool:
    """prefix_filter.py schema with policy settings and threshold sweeps."""
    return isinstance(data, dict) and all(
        key in data for key in ("settings", "threshold_quantiles", "max_restarts")
    )


def collect_typed_results(results: dict):
    """Split raw loaded results by schema."""
    probe = {}
    prefix_filter = {}
    for model in sorted(results):
        for ds in sorted(results[model]):
            data = results[model][ds]
            if is_probe_result(data):
                probe.setdefault(model, {})[ds] = data
            elif is_prefix_filter_result(data):
                prefix_filter.setdefault(model, {})[ds] = data
    return probe, prefix_filter


def fmt(v, digits=3):
    """Format a float to fixed decimal places."""
    if v is None:
        return "—"
    return f"{v:.{digits}f}"


def pm(mean, std, digits=3):
    """Format mean ± std."""
    return f"{mean:.{digits}f} ± {std:.{digits}f}"


def best_layer(layers_dict):
    """Return the layer key with highest combined AUC."""
    return max(layers_dict, key=lambda l: layers_dict[l]["combined"]["roc_auc_mean"])


def generate_markdown(results: dict, output_path: str):
    """Generate a markdown summary of all results."""
    probe_results, prefix_filter_results = collect_typed_results(results)

    lines = []
    lines.append("# Results Summary")
    lines.append("")
    lines.append("*Auto-generated by `summarize.py` from per-stage result JSONs.*")
    lines.append("")

    # --- Overview table ---
    if probe_results:
        lines.append("## Overview")
        lines.append("")
        lines.append("| Model | Dataset | N | Correct | Incorrect | Entropy AUC | Best Layer | Mahal AUC | Combined AUC | Δ (raw) | Δ (len-ctrl) |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|---|")

        for model in sorted(probe_results):
            for ds in sorted(probe_results[model]):
                if ds.endswith("_cross"):
                    continue
                d = probe_results[model][ds]
                n_c = d["n_correct"]
                n_i = d["n_incorrect"]
                n = n_c + n_i
                ent = d["entropy_baseline"]["roc_auc_mean"]
                bl = best_layer(d["layers"])
                lr = d["layers"][bl]
                mah = lr["mahalanobis_only"]["roc_auc_mean"]
                comb = lr["combined"]["roc_auc_mean"]
                delta = lr["delta_vs_entropy"]
                lc_delta = lr.get("length_controlled_delta", None)
                lines.append(
                    f"| {model} | {ds} | {n} | {n_c} ({100*n_c/n:.0f}%) | {n_i} "
                    f"| {fmt(ent)} | L{bl} | {fmt(mah)} | **{fmt(comb)}** "
                    f"| {delta:+.3f} | {'+' if lc_delta and lc_delta >= 0 else ''}{fmt(lc_delta)} |"
                )
        lines.append("")

    # --- Per-layer detail ---
    if probe_results:
        lines.append("## Per-layer detail")
        lines.append("")
        for model in sorted(probe_results):
            for ds in sorted(probe_results[model]):
                if ds.endswith("_cross"):
                    continue
                d = probe_results[model][ds]
                lines.append(f"### {model} / {ds}")
                lines.append("")
                ent = d["entropy_baseline"]["roc_auc_mean"]
                ent_std = d["entropy_baseline"]["roc_auc_std"]
                lines.append(f"Entropy-only baseline: {pm(ent, ent_std)}")
                lines.append("")
                lines.append("| Layer | Mahal-only | Combined | Δ (raw) | Δ (len-ctrl) | Conf-wrong p |")
                lines.append("|---|---|---|---|---|---|")
                for layer in sorted(d["layers"], key=int):
                    lr = d["layers"][layer]
                    mah = lr["mahalanobis_only"]["roc_auc_mean"]
                    mah_std = lr["mahalanobis_only"]["roc_auc_std"]
                    comb = lr["combined"]["roc_auc_mean"]
                    comb_std = lr["combined"]["roc_auc_std"]
                    delta = lr["delta_vs_entropy"]
                    lc = lr.get("length_controlled_delta", None)
                    cw = lr["confident_wrong"]
                    cw_p = cw.get("mannwhitney_pvalue")
                    if cw.get("skipped") or cw_p is None:
                        cw_cell = "—"
                    elif isinstance(cw_p, float) and math.isnan(cw_p):
                        cw_cell = "—"
                    else:
                        sig = "***" if cw_p < 0.01 else ("*" if cw_p < 0.05 else "ns")
                        cw_cell = f"{cw_p:.2e} {sig}"
                    lines.append(
                        f"| L{layer} | {pm(mah, mah_std)} | {pm(comb, comb_std)} "
                        f"| {delta:+.4f} | {lc:+.4f} | {cw_cell} |"
                    )
                lines.append("")

    # --- Cross-model transfer ---
    has_cross = any(
        ds.endswith("_cross")
        for model in probe_results
        for ds in probe_results[model]
    )
    if has_cross:
        lines.append("## Cross-model Mahalanobis transfer")
        lines.append("")
        lines.append("Reference manifold fitted on the *other* model's correct traces,")
        lines.append("then used to classify *this* model's traces.")
        lines.append("")
        lines.append("| Model | Dataset | Layer | Native Mahal | Cross Mahal | Transfer % | Cross Combined | Clf Mahal | Clf Combined |")
        lines.append("|---|---|---|---|---|---|---|---|---|")

        for model in sorted(probe_results):
            for ds in sorted(probe_results[model]):
                if not ds.endswith("_cross"):
                    continue
                base_ds = ds.replace("_cross", "")
                d = probe_results[model][ds]
                native_data = probe_results.get(model, {}).get(base_ds, {})
                cross = d.get("cross_model_transfer", {})

                for layer in sorted(cross, key=int):
                    cr = cross[layer]
                    cross_mah = cr["cross_mahal_only"]["roc_auc_mean"]
                    cross_comb = cr["cross_combined"]["roc_auc_mean"]
                    native_mah = native_data.get("layers", {}).get(layer, {}).get(
                        "mahalanobis_only", {}
                    ).get("roc_auc_mean", None)
                    transfer_pct = (
                        f"{100 * cross_mah / native_mah:.0f}%"
                        if native_mah and native_mah > 0
                        else "—"
                    )
                    clf_mah = cr.get("clf_transfer_mahal_only", {}).get("roc_auc", None)
                    clf_comb = cr.get("clf_transfer_combined", {}).get("roc_auc", None)
                    lines.append(
                        f"| {model} | {base_ds} | L{layer} "
                        f"| {fmt(native_mah)} | {fmt(cross_mah)} | {transfer_pct} "
                        f"| {fmt(cross_comb)} | {fmt(clf_mah)} | {fmt(clf_comb)} |"
                    )
        lines.append("")

    # --- Difficulty stratification ---
    has_diff = any(
        "difficulty_stratification" in probe_results[model].get(ds, {})
        for model in probe_results
        for ds in probe_results[model]
    )
    if has_diff:
        lines.append("## Difficulty stratification (MATH-500)")
        lines.append("")
        for model in sorted(probe_results):
            for ds in sorted(probe_results[model]):
                if ds.endswith("_cross"):
                    continue
                d = probe_results[model][ds]
                diff = d.get("difficulty_stratification")
                if not diff:
                    continue
                lines.append(f"### {model} / {ds}")
                lines.append("")
                lines.append("| Bucket | N | Correct | Incorrect | Ent AUC | Comb AUC | Δ | Combined 95% CI | Entropy 95% CI |")
                lines.append("|---|---|---|---|---|---|---|---|---|")
                for bucket in ["level_1", "level_2", "level_3", "level_4", "level_5",
                               "easy_1-2", "medium_3", "hard_4-5"]:
                    dr = diff.get(bucket)
                    if not dr or dr.get("skipped"):
                        continue
                    n = dr["n_total"]
                    nc = dr["n_correct"]
                    ni = dr["n_incorrect"]
                    ea = dr["entropy_only"]["roc_auc_mean"]
                    ca = dr["combined"]["roc_auc_mean"]
                    delta = dr["delta"]
                    ci = dr.get("bootstrap_ci", {})
                    cci = ci.get("combined_ci95", (None, None))
                    eci = ci.get("entropy_ci95", (None, None))
                    cci_str = f"[{cci[0]:.3f}, {cci[1]:.3f}]" if cci[0] is not None else "—"
                    eci_str = f"[{eci[0]:.3f}, {eci[1]:.3f}]" if eci[0] is not None else "—"
                    lines.append(
                        f"| {bucket} | {n} | {nc} | {ni} | {fmt(ea)} | {fmt(ca)} "
                        f"| {delta:+.3f} | {cci_str} | {eci_str} |"
                    )
                lines.append("")

    # --- Subject stratification ---
    has_subj = any(
        "subject_stratification" in probe_results[model].get(ds, {})
        for model in probe_results
        for ds in probe_results[model]
    )
    if has_subj:
        lines.append("## Subject stratification (MATH-500)")
        lines.append("")
        for model in sorted(probe_results):
            for ds in sorted(probe_results[model]):
                if ds.endswith("_cross"):
                    continue
                d = probe_results[model][ds]
                subj = d.get("subject_stratification")
                if not subj:
                    continue
                lines.append(f"### {model} / {ds}")
                lines.append("")
                lines.append("| Subject | N | Correct | Incorrect | Ent AUC | Mahal AUC | Comb AUC | Δ |")
                lines.append("|---|---|---|---|---|---|---|---|")
                for subject in sorted(subj):
                    sr = subj[subject]
                    if sr.get("skipped"):
                        continue
                    n = sr["n_total"]
                    nc = sr["n_correct"]
                    ni = sr["n_incorrect"]
                    ea = sr["entropy_only"]["roc_auc_mean"]
                    ma = sr["mahalanobis_only"]["roc_auc_mean"]
                    ca = sr["combined"]["roc_auc_mean"]
                    delta = sr["delta"]
                    lines.append(
                        f"| {subject} | {n} | {nc} | {ni} | {fmt(ea)} | {fmt(ma)} | {fmt(ca)} | {delta:+.3f} |"
                    )
                lines.append("")

    # --- Prefix filtering ---
    has_prefix_filter = any(prefix_filter_results.get(model) for model in prefix_filter_results)
    if has_prefix_filter:
        lines.append("## Prefix filtering (abort/restart simulation)")
        lines.append("")
        lines.append(
            "Each row reports the best operating point for a model/dataset "
            "(highest Pass@1 delta, then higher token savings)."
        )
        lines.append("")
        lines.append("| Model | Dataset | Setting | Quantile | Pass@1 | Baseline Pass@1 | ΔPass | Token Savings | False Abort Rate | Avg Aborts / Problem | Max Restarts |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|---|")

        for model in sorted(prefix_filter_results):
            for ds in sorted(prefix_filter_results[model]):
                data = prefix_filter_results[model][ds]
                best_setting = None
                best_payload = None

                for setting in data.get("settings", {}).values():
                    if setting.get("skipped"):
                        continue
                    for payload in setting.get("thresholds", {}).values():
                        if payload.get("skipped"):
                            continue
                        if best_payload is None:
                            best_setting = setting
                            best_payload = payload
                            continue
                        better_delta = payload["pass_delta_vs_baseline"] > best_payload["pass_delta_vs_baseline"]
                        same_delta = payload["pass_delta_vs_baseline"] == best_payload["pass_delta_vs_baseline"]
                        better_savings = payload["token_savings_mean"] > best_payload["token_savings_mean"]
                        if better_delta or (same_delta and better_savings):
                            best_setting = setting
                            best_payload = payload

                if best_setting is None or best_payload is None:
                    lines.append(
                        f"| {model} | {data.get('dataset', ds)} | — | — | — | — | — | — | — | — | {data.get('max_restarts', '—')} |"
                    )
                    continue

                layer = best_setting.get("layer")
                layer_label = "-" if layer is None else f"L{layer}"
                setting_label = (
                    f"{best_setting['score_kind']} {layer_label} k={best_setting['prefix_len']}"
                )
                baseline = best_setting["baseline"]["pass_at_1_mean"]
                lines.append(
                    f"| {model} | {data.get('dataset', ds)} | {setting_label} "
                    f"| {best_payload['quantile']:.2f} | {best_payload['pass_at_1_mean']:.3f} "
                    f"| {baseline:.3f} | {best_payload['pass_delta_vs_baseline']:+.3f} "
                    f"| {best_payload['token_savings_mean']:+.3f} | {best_payload['false_abort_rate']:.3f} "
                    f"| {best_payload['avg_aborts_per_problem']:.3f} | {data.get('max_restarts', '—')} |"
                )
        lines.append("")

    md = "\n".join(lines) + "\n"
    with open(output_path, "w") as f:
        f.write(md)
    print(f"Summary written to {output_path}")


def generate_combined_json(results: dict, output_path: str):
    """Write a combined JSON with all results."""
    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Combined JSON written to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Aggregate results into summary tables")
    parser.add_argument("--results_dir", type=str, default="results",
                        help="Root results directory")
    parser.add_argument("--output_dir", type=str, default="results",
                        help="Where to write summary files")
    args = parser.parse_args()

    results = load_results(args.results_dir)
    os.makedirs(args.output_dir, exist_ok=True)

    md_path = os.path.join(args.output_dir, "SUMMARY.md")
    json_path = os.path.join(args.output_dir, "all_results.json")

    generate_markdown(results, md_path)
    generate_combined_json(results, json_path)


if __name__ == "__main__":
    main()
